sudo: true
language: python
cache: pip

services:
- docker

matrix:
  include:
  - python: "2.7"
    env: STLS=setuptools
  - python: "3.3"
    env: STLS=setuptools~=39.2
  - python: "3.4"
    env: STLS=setuptools
  - python: "3.5"
    env: STLS=setuptools
  - python: "3.6"
    env: STLS=setuptools
  - python: pypy
    env: STLS=setuptools
  - python: pypy3.5
    env: STLS=setuptools
  allow_failures:
  - python: pypy
  - python: pypy3.5

before_install:
- docker pull pwntr/samba-alpine
- pip install -U $STLS wheel

install:
- pip install .[dev,test]

script:
- green

after_script:
- codecov

before_deploy:
- python setup.py check -rms

deploy:
  provider: pypi
  user: althonos
  password:
    secure: qcM7Q7KIH4U/idf7FRDmcVToTl7QbiSfNctJL6LYEOPxNdJSJADZCW73UsROTaCFHDZtmow+pXitnOwbREp7RpJsT6DVLGIuOdD1LMmxvDhZITc9mLeflfncmOmHcDk/QUHOPpmGpKGpeHIhLxwdd5pMHyrlQjkgWBRzstYLvbsoauV3pN4YD1OJSEUKyWDhXmZ3rcD5F3j/aiCKb05wVqIAdDJFmHJp4k9VNdVp+kmh8L4KAaaWVIYVSJ4LJznmgn+wYhtZdDWKTU7yYL94NR73bQU0Sd806d24TvJ7pqwaD6FvlXFmstXlnlKqO1jt81rPKpNw/wmUhNGGZB+YmSI7yz89rsBUnHCdiYY3lqpQr9XGgCcV0thQDtRqjUi8lGNcoih4Vb/YfChNuFKODVArZ5i1pZwrTQ9I+zWObKc/vZp1FHCewX+BoYzCRKgOxWZcM0Il28Y+7O7Bmzpjh+i18Su/a/7SjNKbkn7JKsSXzhgtTeWjBBQkDtzzB2mWLcUL0nLXaCZhbYJ9naTGiipv2o9NPU+kMZoiEUKhOV36lViMMazgSDZ6iiRbX+endQUG85tYtTBCJ1NWdXbBFZaInddy+vppLjL1XBSV45Aj/62gLyZ/XhmQzBaewrmmM42TKI9C6K8V3K+qsOmow1b6G8AgfwzTGktPcjWfn6o=
  on:
    tags: true
    repo: althonos/fs.smbfs
    python: 3.6
  distributions: sdist bdist_wheel
  server: https://upload.pypi.org/legacy/
  skip_upload_docs: true

notifications:
  email:
  - althonosdev@gmail.com
